const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const world=require('../src/renderer/assets/world.json'),context={window:{},atob};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/renderer/js/nav.js'),'utf8'),context);const nav=new context.window.DesklyNav(world.grid);
// Use actual player radius and eight collision probes, not nearest-free snapping.
const free=new Uint8Array(nav.nx*nav.nz),seen=new Uint8Array(free.length);
for(let z=0;z<nav.nz;z++)for(let x=0;x<nav.nx;x++){const p=nav.center(x,z);let blocked=nav.blockedAt(p.x,p.z);for(let k=0;k<8&&!blocked;k++){const a=k*Math.PI/4;blocked=nav.blockedAt(p.x+Math.cos(a)*.22,p.z+Math.sin(a)*.22);}free[z*nav.nx+x]=!blocked;}
const [sx,sz]=nav.ci(20,4),queue=[sz*nav.nx+sx];seen[queue[0]]=1;
for(let i=0;i<queue.length;i++){const k=queue[i],x=k%nav.nx,z=Math.floor(k/nav.nx);for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,zz=z+dz,j=zz*nav.nx+xx;if(nav.inb(xx,zz)&&free[j]&&!seen[j]){seen[j]=1;queue.push(j);}}}
const reachable=queue.map(k=>nav.center(k%nav.nx,Math.floor(k/nav.nx)));
test('every enclosed office room has a player-sized route from reception',()=>{const rooms={Kitchen:[.3,.3,8.8,7.8],Women:[33.3,.3,39.7,3.7],Men:[33.3,4.3,39.7,7.7],Training:[40.3,.3,48.7,7.7],Wellness:[49.3,.3,52.2,7.7],FirstAid:[52.8,.3,55.2,7.7],Mail:[55.8,.3,59.7,7.7],CEO:[.3,25,9.7,35.7],Boardroom:[10.3,28.3,17.7,35.7],Meeting1:[18.3,28.3,21.7,35.7],Meeting2:[22.3,28.3,25.7,35.7],Meeting3:[26.3,28.3,29.7,35.7],HR:[30.3,28.3,35.7,35.7],Finance:[36.3,28.3,41.7,35.7],Server:[42.3,28.3,44.7,35.7],Research:[45.3,28.3,55.7,35.7]};for(const [room,r]of Object.entries(rooms))assert.ok(reachable.filter(p=>p.x>r[0]&&p.x<r[2]&&p.z>r[1]&&p.z<r[3]).length>20,room+' is obstructed');});
test('all physical office activities can be reached within their interaction range',()=>{for(const m of world.markers.filter(m=>['coffee','water','whiteboard','printer','tvwatch','archive','lamp'].includes(m.kind))){const x=m.p[0]-m.f[0]*.7,z=m.p[2]-m.f[1]*.7;assert.ok(reachable.some(p=>Math.hypot(p.x-x,p.z-z)<1.4),m.room+' '+m.kind+' cannot be used');}});
