/* Local office tools. Boards use IndexedDB so imported images never consume AI tokens. */
(function () {
  const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;};
  const button=(text,fn)=>{const b=el('button',text,'btn');b.type='button';b.onclick=fn;return b;};
  let db;
  function database(){return db||(db=new Promise((resolve,reject)=>{const r=indexedDB.open('deskly-freeboards',1);r.onupgradeneeded=()=>r.result.createObjectStore('boards');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}));}
  async function read(room){const d=await database();return new Promise((resolve,reject)=>{const r=d.transaction('boards').objectStore('boards').get(room);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
  async function write(room,board){const d=await database();return new Promise((resolve,reject)=>{const t=d.transaction('boards','readwrite');t.objectStore('boards').put(board,room);t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
  function install(app){
    const ui=app.ui,cache=new Map(),surfaces=new Map(),queues=new Map(),images=new Map();
    const panel=document.querySelector('#panel');
    const originalClose=ui.close.bind(ui);ui.close=function(){panel.classList.remove('office-full');app.player.enabled=!!app.playing;originalClose();};
    function open(kind,title,body){ui.open(kind,ui.hdr(title,'Esc to return to the office'),body);panel.classList.add('office-full');app.player.enabled=false;}
    async function load(room){if(cache.has(room))return cache.get(room);const old=app.life.board(room);const b=await read(room)||{items:old.text?[{id:crypto.randomUUID(),type:'text',text:old.text,x:30,y:30,w:440,h:360,color:'#fff1aa'}]:[]};cache.set(room,b);return b;}
    function paint(room,board){for(const s of surfaces.get(room)||[]){const g=s.canvas.getContext('2d');g.fillStyle='#f8f8f3';g.fillRect(0,0,1200,750);for(const i of board.items){g.fillStyle=i.color||'#e0efff';g.fillRect(i.x,i.y,i.w,i.h);if(i.type==='image'){let image=images.get(i.src);if(image?.complete&&image.naturalWidth)g.drawImage(image,i.x,i.y,i.w,i.h);else if(!image){image=new Image();images.set(i.src,image);image.onload=()=>paint(room,cache.get(room)||board);image.src=i.src;}}else{g.fillStyle='#182630';g.font='22px sans-serif';let y=i.y+30;for(const line of String(i.text||'').split('\n')){let row='';for(const word of line.split(' ')){if(g.measureText(row+' '+word).width>i.w-24){g.fillText(row,i.x+12,y);row=word;y+=28;}else row+=(row?' ':'')+word;}if(y<i.y+i.h-8)g.fillText(row,i.x+12,y);y+=28;if(y>=i.y+i.h-8)break;}}}s.texture.needsUpdate=true;}}
    function persist(room,board,status){paint(room,board);const snapshot=structuredClone(board);const next=(queues.get(room)||Promise.resolve()).catch(()=>{}).then(()=>write(room,snapshot));queues.set(room,next);if(status)status.textContent='Saving…';next.then(()=>{if(status)status.textContent='Saved on this device';},()=>{if(status)status.textContent='Save failed — storage unavailable. Keep this board open and export a backup.';});return next;}
    for(const m of app.world.markers.filter(m=>m.kind==='whiteboard')){const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=750;const texture=new THREE.CanvasTexture(canvas);texture.encoding=THREE.sRGBEncoding;const w=m.room==='Training_Room'?1.5:m.room==='CEO_Office'?2.4:m.room==='Boardroom'?2.3:1.7;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,m.room==='CEO_Office'?1.15:1),new THREE.MeshBasicMaterial({map:texture}));mesh.name='Freeboard_'+m.room;const offset=['CEO_Office','Boardroom'].includes(m.room)?.77:.875;mesh.position.set(m.p[0]+m.f[0]*offset,m.room==='CEO_Office'?1.525:m.room==='Boardroom'?1.45:1.35,m.p[2]+m.f[1]*offset);mesh.rotation.y=Math.atan2(-m.f[0],-m.f[1]);app.world.scene.add(mesh);const list=surfaces.get(m.room)||[];list.push({canvas,texture,mesh});surfaces.set(m.room,list);load(m.room).then(b=>paint(m.room,b)).catch(()=>{});}
    ui.openWhiteboard=async function(marker){const room=marker.room||'CEO_Office';let board;try{board=await load(room);}catch(e){ui.toast('Cannot open board storage: '+e.message);return;}const body=el('div',null,'office-tool');const toolbar=el('div',null,'tool-bar');const status=el('span','Saved on this device');const view=el('div',null,'board-viewport');const sheet=el('div',null,'freeboard');view.append(sheet);const save=()=>persist(room,board,status);let selected=null;
      function draw(){sheet.replaceChildren();for(const item of board.items){const card=el('div',null,'board-item');card.style.cssText=`left:${item.x/12}%;top:${item.y/7.5}%;width:${item.w/12}%;height:${item.h/7.5}%;background:${item.color||'#e0efff'}`;const handle=el('div',item.type==='image'?'Image':item.type==='link'?'Link':'Note','board-handle');const del=button('×',()=>{board.items=board.items.filter(i=>i!==item);draw();save();});handle.append(del);card.append(handle);
        if(item.type==='image'){const img=el('img');img.src=item.src;img.alt='Board reference';card.append(img);}else{const input=el('textarea');input.value=item.text;input.setAttribute('aria-label',item.type==='link'?'Link URL':'Note text');input.oninput=()=>{item.text=input.value.slice(0,6000);save();};card.append(input);if(item.type==='link')card.append(button('Open link',()=>{try{const u=new URL(item.text.trim());if(!['https:','http:'].includes(u.protocol))throw Error();DK.shellExternal(u.href).catch(e=>ui.toast(e.message));}catch{ui.toast('Enter a valid https:// or http:// link.');}}));}
        const resize=el('div','↘','board-resize');card.append(resize);function drag(e,size){e.preventDefault();selected=item;const start={x:e.clientX,y:e.clientY,ix:item.x,iy:item.y,w:item.w,h:item.h};const rect=sheet.getBoundingClientRect();e.target.setPointerCapture(e.pointerId);const move=v=>{const dx=(v.clientX-start.x)*1200/rect.width,dy=(v.clientY-start.y)*750/rect.height;if(size){item.w=Math.max(120,Math.min(1200-item.x,start.w+dx));item.h=Math.max(100,Math.min(750-item.y,start.h+dy));}else{item.x=Math.max(0,Math.min(1200-item.w,start.ix+dx));item.y=Math.max(0,Math.min(750-item.h,start.iy+dy));}card.style.left=item.x/12+'%';card.style.top=item.y/7.5+'%';card.style.width=item.w/12+'%';card.style.height=item.h/7.5+'%';};const end=()=>{e.target.removeEventListener('pointermove',move);e.target.removeEventListener('pointerup',end);e.target.removeEventListener('pointercancel',end);save();};e.target.addEventListener('pointermove',move);e.target.addEventListener('pointerup',end);e.target.addEventListener('pointercancel',end);}handle.onpointerdown=e=>{if(e.target.tagName!=='BUTTON')drag(e,false);};resize.onpointerdown=e=>drag(e,true);card.onclick=()=>selected=item;sheet.append(card);}}
      function add(type,text,src){if(board.items.length>=60){ui.toast('This board supports 60 items.');return;}board.items.push({id:crypto.randomUUID(),type,text:text||'',src,x:30+(board.items.length%5)*40,y:30+(board.items.length%5)*40,w:300,h:220,color:type==='text'?'#fff1aa':'#e0efff'});draw();save();}
      const file=el('input');file.type='file';file.accept='image/png,image/jpeg,image/webp';file.hidden=true;file.onchange=async()=>{const f=file.files[0];if(!f)return;if(f.size>15*1024*1024){ui.toast('Choose an image under 15 MB.');return;}try{const bitmap=await createImageBitmap(f);const c=document.createElement('canvas'),scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));c.width=Math.max(1,Math.round(bitmap.width*scale));c.height=Math.max(1,Math.round(bitmap.height*scale));c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();add('image','',c.toDataURL('image/jpeg',.85));}catch{ui.toast('Could not read that image. Use PNG, JPG or WebP.');}file.value='';};
      toolbar.append(button('+ Note',()=>add('text')),button('+ Link',()=>add('link','https://')),button('+ Image',()=>file.click()),button('Pin latest meeting',()=>add('text',app.life.state.meetings[0]?.summary||'No meeting notes yet.')),button('Colour',()=>{if(selected){selected.color=selected.color==='#fff1aa'?'#d6f0e1':'#fff1aa';draw();save();}}),button('Export backup',()=>{const a=el('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(board)],{type:'application/json'}));a.download=room+'-board.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}),status,file);body.append(toolbar,el('p','Drag a card’s header to move it. Drag its lower corner to resize. Changes save automatically. Images are imported from your computer.'),view);draw();open('whiteboard',room.replaceAll('_',' ')+' · Freeboard',body);
    };
    const oldPin=app.life.pinToBoard.bind(app.life);app.life.pinToBoard=function(room,text){oldPin(room,text);load(room).then(b=>{b.items.push({id:crypto.randomUUID(),type:'text',text:String(text).slice(0,6000),x:40,y:40,w:440,h:360,color:'#d6f0e1'});if(b.items.length>60)b.items.shift();persist(room,b);}).catch(e=>ui.toast('Board notes could not be saved: '+e.message));};
    ui.openBoards=function(){const body=el('div',null,'office-tool');for(const room of surfaces.keys())body.append(button(room.replaceAll('_',' '),()=>ui.openWhiteboard({room})));open('boards','Office whiteboards',body);};
    const lessons=[['Welcome to Deskly','Walk with W A S D, look with your mouse and hold Shift to move faster. E interacts with the thing or person you are looking at. Escape closes a panel or pauses.'],['Find your way','Click the map at the bottom left or press G. Search rooms and teammates, choose a destination and follow its gold route on the map.'],['Meet your team','Walk up to an employee and press E. Review their skills, give a task or invite them for coffee. Tab opens tasks, approvals and the Team controls.'],['Create real work','Open your laptop with L. Choose a project folder and connect an AI provider in settings. Demo mode is for exploring; real output needs a working connector. Review results and permission requests from Tab.'],['Brainstorm together','Interact with a physical whiteboard using E, or open Whiteboards on the laptop or map. Add notes, images and links, drag and resize them. The saved board is visible in the office.'],['Meetings and night shifts','M opens meeting controls. Employees normally leave after 6 PM. Tab → Team → Call everyone back · keep here holds everyone until Send everyone home, including across nights and restarts. Idle employees use no AI tokens.']];
    ui.openGuide=function(step=0){const body=el('div',null,'office-tool guide-page');body.append(el('small',`STEP ${step+1} OF ${lessons.length}`),el('h1',lessons[step][0]),el('p',lessons[step][1]));const bar=el('div',null,'tool-bar');if(step)bar.append(button('Back',()=>ui.openGuide(step-1)));bar.append(button(step===lessons.length-1?'Start exploring':'Next',()=>{if(step===lessons.length-1){localStorage.setItem('deskly.guide.seen','1');ui.close();}else ui.openGuide(step+1);}),button('Explore now',()=>{localStorage.setItem('deskly.guide.seen','1');ui.close();}));body.append(bar);open('guide','Your first day',body);};
    const mm=document.querySelector('#minimap');mm.setAttribute('role','button');mm.tabIndex=0;mm.title='Open office map · G';mm.onclick=()=>ui.openMap();mm.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();ui.openMap();}};
    addEventListener('keydown',e=>{if(e.defaultPrevented||!app.playing||e.target.closest('input,textarea,select'))return;if(e.code==='KeyG'){e.preventDefault();ui.panelKind==='map'?ui.close():ui.openMap();}if(e.code==='F1'){e.preventDefault();ui.openGuide();}});
    const oldEnter=app.enterOffice;app.enterOffice=function(...args){oldEnter(...args);if(app.playing&&!localStorage.getItem('deskly.guide.seen'))ui.openGuide();};
    app.freeboards={load,persist,cache,surfaces};
  }
  async function erase(){if(db){(await db).close();db=null;}return new Promise((resolve,reject)=>{const request=indexedDB.deleteDatabase('deskly-freeboards');request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('Close other Deskly preview tabs before erasing whiteboards.'));});}
  window.DesklyOfficeTools={install,erase};
})();
