/* High resolution floor plan, destination directory and persistent walking guidance. */
(function(){


  const make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;};
  const btn=(text,fn)=>{const b=make('button','map-action',text);b.type='button';b.onclick=fn;return b;};
  function install(app){
    const rooms=app.data.layout.rooms,[x0,z0,x1,z1]=app.data.bounds,mx=x=>(x-x0)/(x1-x0)*480,my=z=>(z1-z)/(z1-z0)*288;
    const ui=app.ui,base=document.createElement('canvas');base.width=1800;base.height=1440;const bg=base.getContext('2d');const world={x0:x0-4,z0:z0-12,w:x1-x0+8,h:z1-z0+18};const X=x=>(x-world.x0)/world.w*base.width,Y=z=>(z1+6-z)/world.h*base.height;
    bg.fillStyle='#182c32';bg.fillRect(0,0,base.width,base.height);bg.fillStyle='#294039';bg.fillRect(X(x0),Y(z0),X(x1)-X(x0),Y(-10)-Y(z0));bg.fillStyle='#b2c2c0';bg.fillRect(X(x0),Y(z1),X(x1)-X(x0),Y(z0)-Y(z1));
    rooms.forEach((r,i)=>{bg.fillStyle=i<10?'#e4e9e4':i<16?'#d3e2da':'#dbe4e8';bg.fillRect(X(r[1]),Y(r[4]),X(r[3])-X(r[1]),Y(r[2])-Y(r[4]));});
    // Use actual collision data, not approximate room rectangles, for walls and furniture.
    const nav=app.nav.office||app.nav;bg.fillStyle='#71858c';for(let z=z0;z<z1;z+=.2)for(let x=x0;x<x1;x+=.2)if(app.nav.blockedAt(x,z,false))bg.fillRect(X(x),Y(z+.2),base.width/world.w*.205,base.height/world.h*.205);
    bg.strokeStyle='#91aab1';bg.lineWidth=2;bg.strokeRect(X(x0),Y(z1),X(x1)-X(x0),Y(z0)-Y(z1));
    let destination=null,path=[],routeT=0;
    const hud=make('div','route-hud');hud.hidden=true;document.querySelector('#hud').append(hud);
    const guide=()=>{if(!destination)return;routeT-=.33;const p=app.player.pos;if(routeT<=0){routeT=2;path=app.nav.path(p,destination.point())||[];}while(path.length&&Math.hypot(path[0].x-p.x,path[0].z-p.z)<.55)path.shift();let distance=0,previous=p;for(const n of path){distance+=Math.hypot(n.x-previous.x,n.z-previous.z);previous=n;}const direct=Math.hypot(destination.point().x-p.x,destination.point().z-p.z);hud.textContent=direct<1.2?'Arrived · '+destination.name:destination.name+' · '+Math.round(distance||direct)+' m · G map · Backspace clear';hud.hidden=!!ui.panelKind;};
    ui.minimap=function(player,employees){const g=ui.mm;g.drawImage(base,X(x0),Y(z1),X(x1)-X(x0),Y(z0)-Y(z1),0,0,480,288);for(const e of employees){if(!e.present)continue;g.fillStyle='#367493';g.beginPath();g.arc(mx(e.pos.x),my(e.pos.z),4,0,7);g.fill();}g.fillStyle='#ffffff';g.strokeStyle='#286f87';g.lineWidth=2;g.beginPath();g.arc(mx(player.pos.x),my(player.pos.z),5,0,7);g.fill();g.stroke();if(destination){const g=ui.mm;g.strokeStyle='#ffcd6d';g.lineWidth=2;g.beginPath();g.moveTo(mx(app.player.pos.x),my(app.player.pos.z));for(const p of path)g.lineTo(mx(p.x),my(p.z));g.stroke();guide();}else hud.hidden=true;};
    ui.openMap=function(){
      const body=make('div','atlas'),side=make('aside','atlas-side'),heading=make('div','atlas-heading'),title=make('h2',null,'Find your way'),search=make('input','atlas-search'),filters=make('div','atlas-filters'),list=make('div','atlas-list'),detail=make('div','atlas-detail');search.placeholder='Search rooms, people, coffee…';search.setAttribute('aria-label','Search destinations');heading.append(make('small',null,'DESKLY / OFFICE DIRECTORY'),title);side.append(heading,search,filters,list,detail);
      const right=make('div','atlas-right'),tools=make('div','atlas-toolbar'),viewport=make('div','atlas-view'),canvas=make('canvas'),legend=make('div','atlas-legend');viewport.append(canvas);right.append(tools,viewport,legend);body.append(side,right);let filter='All',zoom=1,pan={x:0,y:0},selected=destination,previewPath=path,showPeople=true,showFacilities=true,metrics;
      const places=rooms.map(r=>({name:r[0],type:'Rooms',room:r[5],point:()=>{const marks=app.world.markers.filter(m=>m.room===r[5]);const m=marks.find(m=>m.kind==='whiteboard')||marks.find(m=>m.kind==='chair')||marks[0];return m?{x:m.p[0]-m.f[0]*.7,z:m.p[2]-m.f[1]*.7}:{x:(r[1]+r[3])/2,z:(r[2]+r[4])/2};}}));
      for(const e of app.office.employees)places.push({name:e.name,type:'People',employee:e,point:()=>e.pos});
      for(const m of app.world.markers.filter(m=>['coffee','water','whiteboard','printer'].includes(m.kind)))places.push({name:(m.kind==='whiteboard'?'Whiteboard':m.kind[0].toUpperCase()+m.kind.slice(1))+' · '+m.room.replaceAll('_',' '),type:'Facilities',marker:m,point:()=>({x:m.p[0]-m.f[0]*.7,z:m.p[2]-m.f[1]*.7})});
      function results(){list.replaceChildren();const matches=places.filter(p=>(filter==='All'||p.type===filter)&&p.name.toLowerCase().includes(search.value.toLowerCase()));for(const p of matches){const row=btn(p.name,()=>choose(p));row.className='atlas-place'+(selected===p?' selected':'');const sub=make('small',null,p.employee?(p.employee.present?(p.employee.activity||p.employee.role):'Away · call back from Team'):p.type);row.append(sub);list.append(row);}if(!matches.length)list.append(make('p',null,'No matching destinations.'));}
      function choose(p){selected=p;detail.replaceChildren(make('h3',null,p.name));if(p.employee&&!p.employee.present){detail.append(make('p',null,'This employee is away.'),btn('Open team controls',()=>ui.openBoard('team')));draw();return;}const route=app.nav.path(app.player.pos,p.point());previewPath=route||[];detail.append(make('p',null,route?.length?'Walking route available':'No walking route is available'),btn('Navigate here',()=>{if(!route?.length){ui.toast('No walkable route to that location.');return;}destination=p;path=route;routeT=0;ui.close();guide();}));if(p.marker?.kind==='whiteboard')detail.append(btn('Open whiteboard',()=>ui.openWhiteboard(p.marker)));results();draw();}
      const screen=p=>({x:metrics.left+X(p.x)*metrics.scale,y:metrics.top+Y(p.z)*metrics.scale});
      function draw(){const r=viewport.getBoundingClientRect();if(!r.width||!r.height)return;const dpr=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);}const g=canvas.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.fillStyle='#101f27';g.fillRect(0,0,r.width,r.height);const scale=Math.min(r.width/base.width,r.height/base.height)*zoom;metrics={scale,left:(r.width-base.width*scale)/2+pan.x,top:(r.height-base.height*scale)/2+pan.y};g.drawImage(base,metrics.left,metrics.top,base.width*scale,base.height*scale);
        const line=selected?previewPath:path;if(line?.length){g.strokeStyle='#e9aa34';g.lineWidth=4;g.lineCap='round';g.beginPath();const start=screen(app.player.pos);g.moveTo(start.x,start.y);for(const n of line){const v=screen(n);g.lineTo(v.x,v.y);}g.stroke();}
        g.textAlign='center';g.textBaseline='middle';for(const r of rooms){const v=screen({x:(r[1]+r[3])/2,z:(r[2]+r[4])/2});const available=(r[3]-r[1])*base.width/world.w*scale-8;if(available<34)continue;g.font='600 '+Math.max(9,Math.min(14,10*zoom))+'px sans-serif';const lines=[];let row='';for(const word of r[0].split(' ')){if(row&&g.measureText(row+' '+word).width>available-8){lines.push(row);row=word;}else row+=(row?' ':'')+word;}if(row)lines.push(row);const width=Math.min(available,Math.max(...lines.map(t=>g.measureText(t).width))+10),height=lines.length*15+6;g.fillStyle='#ffffffeb';g.fillRect(v.x-width/2,v.y-height/2,width,height);g.fillStyle='#253d49';lines.forEach((t,i)=>g.fillText(t,v.x,v.y+(i-(lines.length-1)/2)*15,available-8));}
        function dot(p,color,size){const v=screen(p);g.fillStyle=color;g.strokeStyle='#fff';g.lineWidth=2;g.beginPath();g.arc(v.x,v.y,size,0,7);g.fill();g.stroke();}
        if(showPeople)for(const e of app.office.employees)if(e.present)dot(e.pos,'#387ca3',5);if(showFacilities)for(const p of places)if(p.type==='Facilities')dot(p.point(),'#748963',3);
        if(selected&&(!selected.employee||selected.employee.present))dot(selected.point(),'#d39028',9);const p=screen(app.player.pos),f=app.player.forward();g.save();g.translate(p.x,p.y);g.rotate(Math.atan2(f.x,f.z));g.fillStyle='#fff';g.strokeStyle='#237f90';g.lineWidth=3;g.beginPath();g.moveTo(0,-12);g.lineTo(8,8);g.lineTo(0,4);g.lineTo(-8,8);g.closePath();g.fill();g.stroke();g.restore();
      }
      function zoomAt(amount,x,y){if(!metrics)return;const next=Math.max(.7,Math.min(4,zoom*amount)),ratio=next/zoom;const r=viewport.getBoundingClientRect();pan.x=(pan.x+r.width/2-x)*ratio-r.width/2+x;pan.y=(pan.y+r.height/2-y)*ratio-r.height/2+y;zoom=next;draw();}
      let drag=null;viewport.onpointerdown=e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,pan:{...pan},moved:false};viewport.setPointerCapture(e.pointerId);};viewport.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved ||= Math.hypot(dx,dy)>4;if(drag.moved){pan={x:drag.pan.x+dx,y:drag.pan.y+dy};draw();}};viewport.onpointerup=e=>{if(!drag)return;if(!drag.moved&&metrics){const r=viewport.getBoundingClientRect(),wx=world.x0+(e.clientX-r.left-metrics.left)/metrics.scale/base.width*world.w,wz=42-(e.clientY-r.top-metrics.top)/metrics.scale/base.height*world.h;const nearest=places.filter(p=>!p.employee||p.employee.present).map(p=>({p,d:Math.hypot(p.point().x-wx,p.point().z-wz)})).sort((a,b)=>a.d-b.d)[0];if(nearest?.d<1.8)choose(nearest.p);else choose({name:'Custom waypoint',type:'Waypoint',point:()=>({x:wx,z:wz})});}drag=null;};viewport.onpointercancel=()=>drag=null;viewport.addEventListener('wheel',e=>{e.preventDefault();const r=viewport.getBoundingClientRect();zoomAt(e.deltaY<0?1.15:1/1.15,e.clientX-r.left,e.clientY-r.top);},{passive:false});
      for(const name of ['All','Rooms','People','Facilities']){const b=btn(name,()=>{filter=name;for(const c of filters.children)c.classList.toggle('active',c===b);results();});if(name==='All')b.classList.add('active');filters.append(b);}search.oninput=results;
      tools.append(make('span',null,'GROUND FLOOR'),btn('−',()=>zoomAt(1/1.2,viewport.clientWidth/2,viewport.clientHeight/2)),btn('+',()=>zoomAt(1.2,viewport.clientWidth/2,viewport.clientHeight/2)),btn('Fit map',()=>{zoom=1;pan={x:0,y:0};draw();}),btn('Locate me',()=>{zoom=2;const scale=Math.min(viewport.clientWidth/base.width,viewport.clientHeight/base.height)*zoom;pan={x:(base.width/2-X(app.player.pos.x))*scale,y:(base.height/2-Y(app.player.pos.z))*scale};draw();}),btn('Clear route',()=>{destination=null;path=[];previewPath=[];selected=null;hud.hidden=true;detail.replaceChildren();draw();}),btn('People',()=>{showPeople=!showPeople;draw();}),btn('Facilities',()=>{showFacilities=!showFacilities;draw();}));legend.textContent='▲ You    ● Team    ● Facilities    ● Destination   — Walking route     Drag to pan · Scroll to zoom · G / Esc close';
      ui.open('map',ui.hdr('Office atlas','G to toggle · click a destination, then Navigate here'),body);document.querySelector('#panel').classList.add('office-full');app.player.enabled=false;ui.onRender=()=>{guide();draw();};results();requestAnimationFrame(draw);
    };
    addEventListener('keydown',e=>{if(e.defaultPrevented||e.repeat||!app.playing||e.target.closest('input,textarea,select')||e.ctrlKey||e.altKey||e.metaKey)return;const actions={KeyB:()=>ui.openBoards(),KeyH:()=>ui.openGuide(),KeyT:()=>ui.openBoard('tasks'),KeyN:()=>ui.openBoard('team'),Backspace:()=>{destination=null;path=[];hud.hidden=true;}};if(actions[e.code]){e.preventDefault();actions[e.code]();}});
    app.atlas={rooms,base,guide,get route(){return path;},get destination(){return destination;}};
  }
  window.DesklyAtlas={install};
})();
